### ISSUE TITLE
divop directory should be renamed divergence, and also include the compute_diveu functionality

### ISSUE THREAD

**Issue by knutsvk** [AMReX-Codes/incflo#10]

**Comment by drummerdoc** [comment]
Keep in mind that PeleLM reimplements calc_divu, for example, as it does a bunch of other functions.  This is one of the fundamental flaws of C++...

**Comment by knutsvk** [comment]
Yes, but calc_divu and many of the other functions in IAMR do not have the same format and names in this code, so if PeleLM is going to use incflo at any point the work will probably need to happen on that end.
