### ISSUE TITLE
Qs about connect the Blitz with incflo

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/incflo#24]
Hi Knutsvk,

I downloaded the Blitz to the HPC (I do not have the root privilege) and added the following lines in the Make.incflo file in the incflo directory.

AMREX_HOME ?= ../../../amrex-master
##Add BLITZ_HOME
BLITZ_HOME ?= /mnt/lustre2/lshen/zengx372/EBIAMR/blitz-0.10/blitz/
INCLUDE_LOCATIONS += $(BLITZ_HOME)
##

It seems there still be some compiling questions while compiling the Blitz. See the error log (https://github.com/ruihai0925/Qs-about-AMReX/blob/master/Qs_compile_incflo), could you give me some suggestions?

Thanks so much.

Jordan

**Comment by ruihai0925** [comment]
Solved. It seems that a higher version of gcc is needed for fixing the above bug.

**Comment by knutsvk** [comment]
Hello Jordan, 

For me this has not been a problem. I am using Blitz 0.10. I have tried with gcc 5.4.0 and gcc 4.8.5 without problem, and also the LLVM compilers on macOS, version 10.0.0. 

It does seem strange that you received the error from /apps/gnu_compiler/4.9.3/... after changing to 6.1.0. Maybe you should try a `make realclean` in the run directory and compile from scratch?

**Comment by knutsvk** [comment]
PS: I think there is a plan to ship Blitz with amrex soon, so that this will be taken care of automatically. Will update incflo when that happens.

**Comment by knutsvk** [comment]
Three months without further comments.
