### ISSUE TITLE
Single Precision (Float) Compilation Error

### ISSUE THREAD

**Issue by shivajimedida** [AMReX-Codes/incflo#38]
Please see below compilation error when building with PRECISION = FLOAT

../src/incflo_compute_dt.cpp(102): error: no instance of overloaded function "amrex::max" matches the argument list
            argument types are: (double, amrex::Real)

../src/incflo_compute_dt.cpp(110): error: no instance of overloaded function "std::max" matches the argument list
            argument types are: (amrex::Real, double)

../src/incflo_compute_dt.cpp(156): error: no instance of overloaded function "amrex::min" matches the argument list
            argument types are: (amrex::Real, double)

../src/incflo_compute_dt.cpp(160): error: no instance of overloaded function "amrex::min" matches the argument list
            argument types are: (amrex::Real, double)

**Comment by asalmgren** [comment]
incflo now compiles with single precision
