### ISSUE TITLE
Rayleigh Taylor Benchmark diverges with MPI+CUDA

### ISSUE THREAD

**Issue by shivajimedida** [AMReX-Codes/incflo#39]
The Rayleigh Taylor benchmark fails at timestep 11 when run with MPI+CUDA on a single MPI node with a single Nvidia RTX 6000 graphics card. It runs to completion with just MPI. The GNUMakefile and input file are identical to the repo on github.

https://github.com/AMReX-Codes/incflo/blob/master/test_no_eb/benchmark.rayleigh_taylor

Step 11: from old_time 1.141831059 to new time 1.243923241 with dt = 0.1020921823.
MLMG: Initial rhs               = 0.3723365619
MLMG: Initial residual (resid0) = 0.3723365619
MLMG: Final Iter. 15 resid, resid/bnorm = 3.127220705e-13, 8.398908474e-13
MLMG: Timers: Solve = 1.00260317 Iter = 0.966925987 Bottom = 0.044780084
Diffusing velocity components all together...
MLMG: Initial rhs               = 0.02536299902
MLMG: Initial residual (resid0) = 0.01282485193
MLMG: Failed to converge after 100 iterations. resid, resid/bnorm = 1.116778747e-09, 4.403180974e-08
amrex::Abort::0::MLMG failed !!!
SIGABRT

**Comment by asalmgren** [comment]
This has been fixed, and the Rayleigh-Taylor test has been added to the CPU and GPU regression tests.
