### ISSUE TITLE
Run EB test with different refinement ratios in the x and y direction

### ISSUE THREAD

**Issue by jl2212** [AMReX-Codes/incflo#76]
When running the benchmark.eb_flow_const_velx test in test_2d folder using different refinement ratio in x and y direction by setting 'amr.ref_ratio_vect   =  2 1', I got an out of bound error. 
![Screenshot_2023-08-02_16-06-06](https://github.com/AMReX-Codes/incflo/assets/83776700/4766d34a-10e8-4cea-a310-66268c4b7cb4)

Running the code in the debug mode, we found the error might to do with the following section,

IndexSpaceImp<G>::getLevel (const Geometry& geom) const
{
    auto it = std::find(std::begin(m_domain), std::end(m_domain), geom.Domain());
    int i = std::distance(m_domain.begin(), it);
    return m_gslevel[i];
}

The geom.Domain() doesn't fall into m_domain
![Screenshot_2023-08-02_15-56-00](https://github.com/AMReX-Codes/incflo/assets/83776700/f6b7b709-3a76-412c-a1db-8c6dbb0b4749)

I was running the code using AMReX 23.08 with Incflo 23.08.

**Comment by WeiqunZhang** [comment]
This is not supported. We must have dx == dy when EB is on.

**Comment by asalmgren** [comment]
I will add an error inside incflo to enforce this.
