### ISSUE TITLE
The documentation online page of incflo was missing

### ISSUE THREAD

**Issue by Sunbuyu** [AMReX-Codes/incflo#86]
The site `https://amrex-codes.github.io/incflo/docs_html/` is not working properly. 
![image](https://github.com/AMReX-Fluids/incflo/assets/52070155/8fbe8192-b606-4bc7-8cde-9df0e41a3f18)
Could you please fix it? Compiling on my local host is sometimes not convenient.

**Comment by WeiqunZhang** [comment]
Thanks for reporting the issue. It should be fixed now.

**Comment by WeiqunZhang** [comment]
Note that the new URL is https://amrex-fluids.github.io/incflo/docs_html/.

**Comment by Sunbuyu** [comment]
Thanks. Now it works.
